---
# This example file will enable R language checks on push or PR to the main
# branch.
# It will also run the checks every weeknight at midnight UTC
#
# Note the @main in `uses:` on the last line. This will call the latest version
# of the workflow from the `main` brnach in the RMI-PACTA/actions repo. You can
# also specify a tag from that repo, or a commit SHA to pin action versions.
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1,2,3,4,5'
  workflow_dispatch:

name: R

permissions: read-all

jobs:
  R-package:
    name: R Package Checks
    uses: RMI-PACTA/actions/.github/workflows/R.yml@main
    secrets: inherit
    with:
      r-cmd-check-matrix: |
        [
          {"os": "macOS-latest", "r": "release"},
          {"os": "windows-latest", "r": "release"},
          {"os": "ubuntu-latest", "r": "release"},
          {"os": "ubuntu-latest", "r": "devel", "http-user-agent": "release"},
          {"os": "ubuntu-latest", "r": "oldrel-1"}
        ]

  dev-r-cmd-check:
    name: R CMD Check (dev dependencies)
    uses: RMI-PACTA/actions/.github/workflows/R-CMD-check.yml@main
    with:
      upgrade-packages: 'TRUE'
      cache-version: 'dev'
      remotes: |
        tidyverse/ggplot2
        daroczig/logger
        r-lib/rlang
        RConsortium/S7
      r-cmd-check-matrix: |
        [
          {"os": "macOS-latest", "r": "release"},
          {"os": "windows-latest", "r": "release"},
          {"os": "ubuntu-latest", "r": "release"},
          {"os": "ubuntu-latest", "r": "devel", "http-user-agent": "release"},
          {"os": "ubuntu-latest", "r": "oldrel-1"}
        ]
